import Foundation

/// Les chaînes de l'interface, dans les trois langues d'affichage de Limbator.
///
/// La langue suit le **profil**, pas la locale du téléphone : un Roumain
/// installé à Lyon a son iPhone en français et veut malgré tout que la
/// pédagogie lui parle roumain. Le repli se fait sur l'anglais, puis sur la clé
/// elle-même — une clé oubliée s'affiche donc telle quelle, ce qui la rend
/// visible au lieu de la faire disparaître silencieusement.
///
/// FICHIER GÉNÉRÉ — ne pas modifier à la main.
/// Source : scripts/gen_localizer.py  ·  Régénérer : python3 scripts/gen_localizer.py
enum L {

    /// Code de la langue courante ("ro", "fr", "en"). Mis à jour depuis le profil.
    static var lang: String = "ro"

    static func t(_ key: String) -> String {
        table(for: lang)[key] ?? tableEN[key] ?? key
    }

    /// Variante interpolée (%@ / %d).
    static func t(_ key: String, _ args: CVarArg...) -> String {
        String(format: t(key), arguments: args)
    }

    /// Les langues romanes proches retombent sur le français plutôt que sur
    /// l'anglais : un italophone lit bien mieux « Orthographe » que « Spelling ».
    private static func table(for code: String) -> [String: String] {
        switch code {
        case "ro": return tableRO
        case "fr": return tableFR
        case "en": return tableEN
        case "it", "es", "pt": return tableFR
        default:   return tableEN
        }
    }

    /// Les clés déclarées — utilisé par les tests pour vérifier que les trois
    /// tables restent alignées.
    static var allKeys: [String] { Array(tableRO.keys).sorted() }


    private static let tableRO: [String: String] = [
        "tab.home": "Acasă",
        "tab.lessons": "Lecții",
        "tab.ortho": "Ortografie",
        "tab.games": "Jocuri",
        "tab.profile": "Profil",
        "gemma.status.starting": "Pornim motorul…",
        "gemma.status.ready": "Gata",
        "gemma.status.offline": "Mod offline · conținut local",
        "gemma.status.preparing": "Pregătim modelul…",
        "gemma.status.loading": "Încărcăm modelul în memorie…",
        "gemma.status.downloading": "Descărcăm %@…",
        "gemma.status.downloading_percent": "Descărcăm %@ · %d %%",
        "gemma.error.not_ready": "Gemma nu este încă pregătit.",
        "gemma.error.bad_json": "Răspuns JSON invalid: %@…",
        "gemma.error.download": "Descărcarea modelului a eșuat: %@",
        "gemma.error.incomplete": "descărcare incompletă",
        "gemma.error.repeated_failure": "Gemma nu s-a putut încărca de mai multe ori — modul offline este activ. Reîncearcă din setări.",
        "gemma.retry": "Reîncearcă",
        "gemma.failed_title": "Gemma indisponibil",
        "gemma.first_launch": "Prima pornire · o singură descărcare",
        "download.error.empty": "Depozitul nu conține niciun fișier.",
        "download.error.url": "Adresă invalidă.",
        "download.error.http": "Eroare HTTP %d. Verifică conexiunea.",
        "download.error.checksum": "Verificarea integrității a eșuat pentru %@.",
        "tts.diag.azure": "Voce neurală Azure fr-FR · online",
        "tts.diag.neural": "Voce neurală franceză pe dispozitiv",
        "tts.diag.apple_premium": "Voce Apple Premium fr-FR",
        "tts.diag.apple_compact": "Voce iOS compactă fr-FR — descarcă vocea Premium din Setări iOS pentru o calitate mai bună",
        "onboarding.tagline": "Învață franceza din română,\ncu o IA care scrie corect",
        "onboarding.badge_gemma": "Gemma 4 · 4B",
        "onboarding.badge_offline": "100% offline",
        "onboarding.badge_voice": "Voce neurală",
        "onboarding.badge_voice_sub": "franceză nativă",
        "onboarding.badge_ortho": "Ortografie",
        "onboarding.badge_ortho_sub": "dictare și acorduri",
        "onboarding.ask_name": "Cum să îți spun?",
        "onboarding.name_placeholder": "Prenumele tău",
        "onboarding.native_language_title": "Limba ta maternă",
        "onboarding.native_language_subtitle": "Totul îți va fi explicat în această limbă.",
        "onboarding.level_title": "Ce nivel ai la franceză?",
        "onboarding.level_subtitle": "Nicio grijă — ne ajustăm din mers.",
        "onboarding.goal_title": "Obiectivul tău zilnic",
        "onboarding.goal_subtitle": "Regularitatea bate intensitatea.",
        "onboarding.minutes_per_day": "minute pe zi",
        "onboarding.back": "Înapoi",
        "onboarding.continue": "Continuă",
        "onboarding.start": "Începem",
        "home.default_name": "Prietene",
        "home.greeting_morning": "Bonjour",
        "home.greeting_afternoon": "Bon après-midi",
        "home.greeting_evening": "Bonsoir",
        "home.stat_days": "zile",
        "home.stat_xp": "XP",
        "home.stat_level": "nivel",
        "home.stat_average": "medie",
        "home.dictation_title": "Dictarea zilei",
        "home.dictation_badge": "+120 XP fără greșeli",
        "home.dictation_cta": "Ascultă și scrie",
        "home.quick_title": "Continuă rapid",
        "home.tile_dictation": "Dictare",
        "home.tile_dictation_sub": "Scrie ce auzi",
        "home.tile_homophone": "Duel de homofone",
        "home.tile_homophone_sub": "a sau à ?",
        "home.tile_tutor": "Tutorul IA",
        "home.tile_tutor_sub": "Întreabă orice",
        "home.tile_story": "Povești",
        "home.tile_story_sub": "Franceza în context",
        "home.word_of_day_title": "Cuvântul zilei",
        "home.review_title": "De revăzut azi",
        "home.review_subtitle": "%d reguli te așteaptă",
        "home.review_empty": "Nimic de revăzut azi. Ai fost la zi.",
        "home.weakness_title": "Punctul tău slab",
        "home.weakness_none": "Încă nu ai făcut destule greșeli ca să spun.",
        "home.stories_title": "Povești",
        "home.stories_all": "Toate poveștile",
        "home.start": "Începe",
        "lessons.title": "Parcurs",
        "lessons.subtitle": "14 lecții, fiecare cu punctul ei de ortografie",
        "lessons.filter_all": "Toate",
        "lessons.minutes": "%d min",
        "lesson.intro": "Introducere",
        "lesson.vocabulary": "Vocabular",
        "lesson.phrases": "Expresii utile",
        "lesson.grammar_tip": "Sfat de gramatică",
        "lesson.cultural_note": "Notă culturală",
        "lesson.ortho_spotlight": "Punctul de ortografie",
        "lesson.mark_complete": "Marchează ca terminată · +50 XP",
        "lesson.completed": "Terminată",
        "lesson.loading": "Gemma pregătește lecția…",
        "lesson.flip": "Întoarce",
        "lesson.translation": "Traducere",
        "lesson.example": "Exemplu",
        "lesson.spelling_note": "Capcana de scriere",
        "lesson.card_index": "%d / %d",
        "lesson.right": "Corect",
        "lesson.wrong": "Greșit",
        "ortho.title": "Ortografie",
        "ortho.subtitle": "Opt șantiere. Fiecare greșeală devine o lecție.",
        "ortho.mastery": "Stăpânire",
        "ortho.modules": "Module",
        "ortho.dictation": "Dictare",
        "ortho.dictation_sub": "Ascultă, scrie, primește corectura",
        "ortho.train": "Antrenează-te",
        "ortho.rules": "Reguli",
        "ortho.drills": "Exerciții",
        "ortho.rule_examples": "Exemple",
        "ortho.rule_exceptions": "Excepții",
        "ortho.mnemonic": "De reținut",
        "ortho.check": "Verifică",
        "ortho.next": "Următorul",
        "ortho.correct": "Corect",
        "ortho.incorrect": "Nu chiar",
        "ortho.explanation": "De ce",
        "ortho.your_answer": "Ce ai scris",
        "ortho.expected": "Forma corectă",
        "ortho.score": "Nota",
        "ortho.out_of_20": "%@ / 20",
        "ortho.replay": "Ascultă din nou",
        "ortho.slower": "Mai rar",
        "ortho.word_by_word": "Cuvânt cu cuvânt",
        "ortho.spell_it": "Litera cu literă",
        "ortho.hint": "Indiciu",
        "ortho.show_translation": "Arată traducerea",
        "ortho.submit": "Corectează-mă",
        "ortho.finish": "Termină",
        "ortho.mistakes_title": "Greșelile tale",
        "ortho.perfect": "Nicio greșeală. Impecabil.",
        "ortho.review_rule": "Revezi regula",
        "ortho.type_here": "Scrie aici ce auzi…",
        "ortho.mastered": "Stăpânit",
        "ortho.not_started": "Neînceput",
        "ortho.due_now": "De revăzut",
        "ortho.rules_count": "%d reguli",
        "ortho.drills_count": "%d exerciții",
        "ortho.session_done": "Sesiune terminată",
        "ortho.accuracy": "Acuratețe",
        "ortho.again": "Încă o serie",
        "ortho.choose_level": "Alege dificultatea",
        "ortho.no_drills": "Niciun exercițiu pentru acest modul deocamdată.",
        "games.title": "Jocuri",
        "games.subtitle": "Zece moduri de a exersa fără să pară temă",
        "game.score": "Scor",
        "game.streak": "Serie",
        "game.round": "Runda %d / %d",
        "game.finish": "Gata",
        "game.replay": "Din nou",
        "game.correct": "Corect",
        "game.wrong": "Greșit",
        "game.tap_start": "Atinge ca să începi",
        "game.loading": "Pregătim runda…",
        "game.result": "%d din %d",
        "game.perfect": "Fără nicio greșeală.",
        "game.xp_earned": "+%d XP",
        "game.hold_record": "Ține apăsat ca să înregistrezi",
        "game.listening": "Te ascult…",
        "game.mic_denied": "Microfonul nu este permis. Activează-l din Setări.",
        "game.spin": "Învârte roata",
        "game.build_sentence": "Construiește fraza",
        "game.reset": "Reia",
        "stories.title": "Povești",
        "stories.subtitle": "Patru povestiri franceze — două dintre ele, românești la origine.",
        "stories.featured": "ÎN PRIM-PLAN",
        "stories.all": "Toate poveștile",
        "stories.chapters": "%d capitole",
        "stories.minutes": "%d min",
        "story.chapter": "Capitolul %d",
        "story.scene_index": "Scena %d / %d",
        "story.loading": "Gemma scrie scena…",
        "story.previous": "Înapoi",
        "story.next": "Mai departe",
        "story.finish": "Termină capitolul",
        "story.vocab": "Cuvinte cheie",
        "story.ortho_note": "Oprire pe cuvânt",
        "story.translation": "Traducere",
        "profile.default_name": "Prietene",
        "profile.level_label": "Nivel %d",
        "profile.xp_label": "%d XP",
        "profile.xp_to_next": "%d până la nivelul %d",
        "profile.stat_streak": "Zile la rând",
        "profile.stat_lessons": "Lecții",
        "profile.stat_badges": "Insigne",
        "profile.stat_dictations": "Dictări",
        "profile.rewards_title": "Recompense",
        "profile.mistakes_title": "Profilul greșelilor tale",
        "profile.mistakes_empty": "Nicio greșeală înregistrată. Începe o dictare.",
        "profile.mistakes_count": "%d greșeli",
        "profile.voice_title": "Vocea",
        "profile.voice_speed": "Viteză",
        "profile.voice_gender": "Timbru",
        "profile.voice_ondevice": "Doar pe dispozitiv",
        "profile.voice_ondevice_sub": "Nicio cerere spre internet pentru voce.",
        "profile.azure_title": "Voce Azure (opțional)",
        "profile.azure_hint": "Adaugă o cheie Azure Speech pentru vocea neurală expresivă. Fără ea, Limbator folosește vocea neurală de pe dispozitiv.",
        "profile.azure_key": "Cheie Azure Speech",
        "profile.azure_region": "Regiune (ex. westeurope)",
        "profile.azure_save": "Salvează și testează",
        "profile.azure_clear": "Șterge cheia",
        "profile.native_language_title": "Limba maternă",
        "profile.level_title": "Nivelul tău",
        "profile.gemma_title": "Modelul Gemma 4",
        "profile.gemma_ready": "Pregătit · 100% offline",
        "profile.gemma_loading": "Se descarcă / se încarcă…",
        "profile.gemma_failed": "Eșuat — atinge pentru a reîncerca",
        "profile.tutor_title": "Tutorul IA",
        "profile.tutor_subtitle": "Discută, întreabă, cere exemple",
        "profile.cache_title": "Cache audio",
        "profile.cache_clear": "Golește (%@)",
        "profile.reset_title": "Resetează profilul",
        "profile.reset_subtitle": "Șterge tot și ia-o de la capăt",
        "profile.reset_confirm": "Resetezi tot?",
        "profile.reset_action": "Resetează",
        "profile.cancel": "Anulează",
        "profile.mastery_title": "Stăpânirea modulelor",
        "profile.words_tracked": "%d cuvinte urmărite",
        "tutor.title": "Tutor",
        "tutor.badge": "Gemma 4 · pe dispozitiv",
        "tutor.placeholder": "Întreabă orice despre franceză…",
        "tutor.greeting": "Bonjour ! Te ajut în %@.\n\nPot să îți explic:\n• de ce se scrie « à » și nu « a »\n• acordul participiului trecut\n• un cuvânt, o expresie, o regulă\n• de ce franceza dublează consoanele",
        "tutor.unavailable": "\n\n[Gemma indisponibil: %@]\n\nModelul se descarcă la prima pornire. Conținutul local rămâne disponibil.",
        "tutor.downloading": "\n\nModelul Gemma se descarcă… %d %%\nÎncearcă din nou într-un moment.",
        "tutor.warming": "\n\nGemma pornește…\nÎncearcă din nou într-un moment.",
        "tutor.send": "Trimite",
        "tutor.stop": "Oprește",
        "component.listen": "Ascultă",
        "component.spell": "Litera cu literă",
        "component.slow": "Mai rar",
        "component.close": "Închide",
        "component.continue": "Continuă",
        "component.new_badge": "Insignă nouă",
    ]

    private static let tableFR: [String: String] = [
        "tab.home": "Accueil",
        "tab.lessons": "Leçons",
        "tab.ortho": "Orthographe",
        "tab.games": "Jeux",
        "tab.profile": "Profil",
        "gemma.status.starting": "Démarrage du moteur…",
        "gemma.status.ready": "Prêt",
        "gemma.status.offline": "Mode hors ligne · contenu local",
        "gemma.status.preparing": "Préparation du modèle…",
        "gemma.status.loading": "Chargement du modèle en mémoire…",
        "gemma.status.downloading": "Téléchargement de %@…",
        "gemma.status.downloading_percent": "Téléchargement de %@ · %d %%",
        "gemma.error.not_ready": "Gemma n'est pas encore prêt.",
        "gemma.error.bad_json": "Réponse JSON invalide : %@…",
        "gemma.error.download": "Le téléchargement du modèle a échoué : %@",
        "gemma.error.incomplete": "téléchargement incomplet",
        "gemma.error.repeated_failure": "Gemma n'a pas pu se charger à plusieurs reprises — le mode hors ligne est actif. Réessaie depuis les réglages.",
        "gemma.retry": "Réessayer",
        "gemma.failed_title": "Gemma indisponible",
        "gemma.first_launch": "Premier lancement · téléchargement unique",
        "download.error.empty": "Le dépôt ne contient aucun fichier.",
        "download.error.url": "Adresse invalide.",
        "download.error.http": "Erreur HTTP %d. Vérifie ta connexion.",
        "download.error.checksum": "La vérification d'intégrité a échoué pour %@.",
        "tts.diag.azure": "Voix neurale Azure fr-FR · en ligne",
        "tts.diag.neural": "Voix neurale française sur l'appareil",
        "tts.diag.apple_premium": "Voix Apple Premium fr-FR",
        "tts.diag.apple_compact": "Voix iOS compacte fr-FR — télécharge la voix Premium dans les Réglages iOS pour une meilleure qualité",
        "onboarding.tagline": "Apprends le français depuis le roumain,\navec une IA qui écrit juste",
        "onboarding.badge_gemma": "Gemma 4 · 4B",
        "onboarding.badge_offline": "100 % hors ligne",
        "onboarding.badge_voice": "Voix neurale",
        "onboarding.badge_voice_sub": "français natif",
        "onboarding.badge_ortho": "Orthographe",
        "onboarding.badge_ortho_sub": "dictée et accords",
        "onboarding.ask_name": "Comment dois-je t'appeler ?",
        "onboarding.name_placeholder": "Ton prénom",
        "onboarding.native_language_title": "Ta langue maternelle",
        "onboarding.native_language_subtitle": "Tout te sera expliqué dans cette langue.",
        "onboarding.level_title": "Quel est ton niveau en français ?",
        "onboarding.level_subtitle": "Aucune inquiétude — on s'ajuste en route.",
        "onboarding.goal_title": "Ton objectif quotidien",
        "onboarding.goal_subtitle": "La régularité bat l'intensité.",
        "onboarding.minutes_per_day": "minutes par jour",
        "onboarding.back": "Retour",
        "onboarding.continue": "Continuer",
        "onboarding.start": "C'est parti",
        "home.default_name": "Ami",
        "home.greeting_morning": "Bonjour",
        "home.greeting_afternoon": "Bon après-midi",
        "home.greeting_evening": "Bonsoir",
        "home.stat_days": "jours",
        "home.stat_xp": "XP",
        "home.stat_level": "niveau",
        "home.stat_average": "moyenne",
        "home.dictation_title": "La dictée du jour",
        "home.dictation_badge": "+120 XP sans faute",
        "home.dictation_cta": "Écoute et écris",
        "home.quick_title": "Reprends vite",
        "home.tile_dictation": "Dictée",
        "home.tile_dictation_sub": "Écris ce que tu entends",
        "home.tile_homophone": "Duel d'homophones",
        "home.tile_homophone_sub": "a ou à ?",
        "home.tile_tutor": "Le tuteur IA",
        "home.tile_tutor_sub": "Demande ce que tu veux",
        "home.tile_story": "Histoires",
        "home.tile_story_sub": "Le français en contexte",
        "home.word_of_day_title": "Le mot du jour",
        "home.review_title": "À revoir aujourd'hui",
        "home.review_subtitle": "%d règles t'attendent",
        "home.review_empty": "Rien à revoir aujourd'hui. Tu es à jour.",
        "home.weakness_title": "Ton point faible",
        "home.weakness_none": "Tu n'as pas encore fait assez de fautes pour que je me prononce.",
        "home.stories_title": "Histoires",
        "home.stories_all": "Toutes les histoires",
        "home.start": "Commencer",
        "lessons.title": "Parcours",
        "lessons.subtitle": "14 leçons, chacune avec son point d'orthographe",
        "lessons.filter_all": "Toutes",
        "lessons.minutes": "%d min",
        "lesson.intro": "Introduction",
        "lesson.vocabulary": "Vocabulaire",
        "lesson.phrases": "Expressions utiles",
        "lesson.grammar_tip": "Astuce de grammaire",
        "lesson.cultural_note": "Note culturelle",
        "lesson.ortho_spotlight": "Le point d'orthographe",
        "lesson.mark_complete": "Marquer comme terminée · +50 XP",
        "lesson.completed": "Terminée",
        "lesson.loading": "Gemma prépare la leçon…",
        "lesson.flip": "Retourner",
        "lesson.translation": "Traduction",
        "lesson.example": "Exemple",
        "lesson.spelling_note": "Le piège d'écriture",
        "lesson.card_index": "%d / %d",
        "lesson.right": "Juste",
        "lesson.wrong": "Faux",
        "ortho.title": "Orthographe",
        "ortho.subtitle": "Huit chantiers. Chaque faute devient une leçon.",
        "ortho.mastery": "Maîtrise",
        "ortho.modules": "Modules",
        "ortho.dictation": "Dictée",
        "ortho.dictation_sub": "Écoute, écris, reçois la correction",
        "ortho.train": "S'entraîner",
        "ortho.rules": "Règles",
        "ortho.drills": "Exercices",
        "ortho.rule_examples": "Exemples",
        "ortho.rule_exceptions": "Exceptions",
        "ortho.mnemonic": "À retenir",
        "ortho.check": "Vérifier",
        "ortho.next": "Suivant",
        "ortho.correct": "Juste",
        "ortho.incorrect": "Pas tout à fait",
        "ortho.explanation": "Pourquoi",
        "ortho.your_answer": "Ce que tu as écrit",
        "ortho.expected": "La forme correcte",
        "ortho.score": "Note",
        "ortho.out_of_20": "%@ / 20",
        "ortho.replay": "Réécouter",
        "ortho.slower": "Plus lentement",
        "ortho.word_by_word": "Mot à mot",
        "ortho.spell_it": "Lettre par lettre",
        "ortho.hint": "Indice",
        "ortho.show_translation": "Voir la traduction",
        "ortho.submit": "Corrige-moi",
        "ortho.finish": "Terminer",
        "ortho.mistakes_title": "Tes fautes",
        "ortho.perfect": "Aucune faute. Impeccable.",
        "ortho.review_rule": "Revoir la règle",
        "ortho.type_here": "Écris ici ce que tu entends…",
        "ortho.mastered": "Maîtrisé",
        "ortho.not_started": "Pas commencé",
        "ortho.due_now": "À revoir",
        "ortho.rules_count": "%d règles",
        "ortho.drills_count": "%d exercices",
        "ortho.session_done": "Séance terminée",
        "ortho.accuracy": "Précision",
        "ortho.again": "Encore une série",
        "ortho.choose_level": "Choisis la difficulté",
        "ortho.no_drills": "Aucun exercice pour ce module pour l'instant.",
        "games.title": "Jeux",
        "games.subtitle": "Dix façons de réviser sans que ça ressemble à un devoir",
        "game.score": "Score",
        "game.streak": "Série",
        "game.round": "Manche %d / %d",
        "game.finish": "Terminer",
        "game.replay": "Rejouer",
        "game.correct": "Juste",
        "game.wrong": "Faux",
        "game.tap_start": "Touche pour commencer",
        "game.loading": "Préparation de la manche…",
        "game.result": "%d sur %d",
        "game.perfect": "Sans la moindre faute.",
        "game.xp_earned": "+%d XP",
        "game.hold_record": "Maintiens pour enregistrer",
        "game.listening": "Je t'écoute…",
        "game.mic_denied": "Le micro n'est pas autorisé. Active-le dans les Réglages.",
        "game.spin": "Tourner la roue",
        "game.build_sentence": "Construis la phrase",
        "game.reset": "Recommencer",
        "stories.title": "Histoires",
        "stories.subtitle": "Quatre récits français — deux d'entre eux venus de Roumanie.",
        "stories.featured": "À LA UNE",
        "stories.all": "Toutes les histoires",
        "stories.chapters": "%d chapitres",
        "stories.minutes": "%d min",
        "story.chapter": "Chapitre %d",
        "story.scene_index": "Scène %d / %d",
        "story.loading": "Gemma écrit la scène…",
        "story.previous": "Précédent",
        "story.next": "Suivant",
        "story.finish": "Terminer le chapitre",
        "story.vocab": "Mots clés",
        "story.ortho_note": "Arrêt sur mot",
        "story.translation": "Traduction",
        "profile.default_name": "Ami",
        "profile.level_label": "Niveau %d",
        "profile.xp_label": "%d XP",
        "profile.xp_to_next": "%d avant le niveau %d",
        "profile.stat_streak": "Jours d'affilée",
        "profile.stat_lessons": "Leçons",
        "profile.stat_badges": "Badges",
        "profile.stat_dictations": "Dictées",
        "profile.rewards_title": "Récompenses",
        "profile.mistakes_title": "Le profil de tes fautes",
        "profile.mistakes_empty": "Aucune faute enregistrée. Commence une dictée.",
        "profile.mistakes_count": "%d fautes",
        "profile.voice_title": "La voix",
        "profile.voice_speed": "Vitesse",
        "profile.voice_gender": "Timbre",
        "profile.voice_ondevice": "Sur l'appareil uniquement",
        "profile.voice_ondevice_sub": "Aucune requête réseau pour la voix.",
        "profile.azure_title": "Voix Azure (facultatif)",
        "profile.azure_hint": "Ajoute une clé Azure Speech pour la voix neurale expressive. Sans elle, Limbator utilise la voix neurale de l'appareil.",
        "profile.azure_key": "Clé Azure Speech",
        "profile.azure_region": "Région (ex. westeurope)",
        "profile.azure_save": "Enregistrer et tester",
        "profile.azure_clear": "Effacer la clé",
        "profile.native_language_title": "Langue maternelle",
        "profile.level_title": "Ton niveau",
        "profile.gemma_title": "Le modèle Gemma 4",
        "profile.gemma_ready": "Prêt · 100 % hors ligne",
        "profile.gemma_loading": "Téléchargement / chargement…",
        "profile.gemma_failed": "Échec — touche pour réessayer",
        "profile.tutor_title": "Le tuteur IA",
        "profile.tutor_subtitle": "Discute, demande, réclame des exemples",
        "profile.cache_title": "Cache audio",
        "profile.cache_clear": "Vider (%@)",
        "profile.reset_title": "Réinitialiser le profil",
        "profile.reset_subtitle": "Tout effacer et recommencer",
        "profile.reset_confirm": "Tout réinitialiser ?",
        "profile.reset_action": "Réinitialiser",
        "profile.cancel": "Annuler",
        "profile.mastery_title": "Maîtrise des modules",
        "profile.words_tracked": "%d mots suivis",
        "tutor.title": "Tuteur",
        "tutor.badge": "Gemma 4 · sur l'appareil",
        "tutor.placeholder": "Demande ce que tu veux sur le français…",
        "tutor.greeting": "Bonjour ! Je t'aide en %@.\n\nJe peux t'expliquer :\n• pourquoi « à » et pas « a »\n• l'accord du participe passé\n• un mot, une expression, une règle\n• pourquoi le français double ses consonnes",
        "tutor.unavailable": "\n\n[Gemma indisponible : %@]\n\nLe modèle se télécharge au premier lancement. Le contenu local reste disponible.",
        "tutor.downloading": "\n\nLe modèle Gemma se télécharge… %d %%\nRéessaie dans un instant.",
        "tutor.warming": "\n\nGemma démarre…\nRéessaie dans un instant.",
        "tutor.send": "Envoyer",
        "tutor.stop": "Arrêter",
        "component.listen": "Écouter",
        "component.spell": "Lettre par lettre",
        "component.slow": "Plus lentement",
        "component.close": "Fermer",
        "component.continue": "Continuer",
        "component.new_badge": "Nouveau badge",
    ]

    private static let tableEN: [String: String] = [
        "tab.home": "Home",
        "tab.lessons": "Lessons",
        "tab.ortho": "Spelling",
        "tab.games": "Games",
        "tab.profile": "Profile",
        "gemma.status.starting": "Starting the engine…",
        "gemma.status.ready": "Ready",
        "gemma.status.offline": "Offline mode · local content",
        "gemma.status.preparing": "Preparing the model…",
        "gemma.status.loading": "Loading the model into memory…",
        "gemma.status.downloading": "Downloading %@…",
        "gemma.status.downloading_percent": "Downloading %@ · %d%%",
        "gemma.error.not_ready": "Gemma is not ready yet.",
        "gemma.error.bad_json": "Invalid JSON reply: %@…",
        "gemma.error.download": "Model download failed: %@",
        "gemma.error.incomplete": "incomplete download",
        "gemma.error.repeated_failure": "Gemma failed to load several times — offline mode is on. Retry from settings.",
        "gemma.retry": "Retry",
        "gemma.failed_title": "Gemma unavailable",
        "gemma.first_launch": "First launch · one-time download",
        "download.error.empty": "The repository contains no files.",
        "download.error.url": "Invalid address.",
        "download.error.http": "HTTP error %d. Check your connection.",
        "download.error.checksum": "Integrity check failed for %@.",
        "tts.diag.azure": "Azure neural fr-FR voice · online",
        "tts.diag.neural": "On-device French neural voice",
        "tts.diag.apple_premium": "Apple Premium fr-FR voice",
        "tts.diag.apple_compact": "Compact iOS fr-FR voice — download the Premium voice in iOS Settings for better quality",
        "onboarding.tagline": "Learn French from Romanian,\nwith an AI that spells correctly",
        "onboarding.badge_gemma": "Gemma 4 · 4B",
        "onboarding.badge_offline": "100% offline",
        "onboarding.badge_voice": "Neural voice",
        "onboarding.badge_voice_sub": "native French",
        "onboarding.badge_ortho": "Spelling",
        "onboarding.badge_ortho_sub": "dictation and agreement",
        "onboarding.ask_name": "What should I call you?",
        "onboarding.name_placeholder": "Your first name",
        "onboarding.native_language_title": "Your native language",
        "onboarding.native_language_subtitle": "Everything will be explained in this language.",
        "onboarding.level_title": "What is your level in French?",
        "onboarding.level_subtitle": "No worries — we adjust as we go.",
        "onboarding.goal_title": "Your daily goal",
        "onboarding.goal_subtitle": "Consistency beats intensity.",
        "onboarding.minutes_per_day": "minutes per day",
        "onboarding.back": "Back",
        "onboarding.continue": "Continue",
        "onboarding.start": "Let's go",
        "home.default_name": "Friend",
        "home.greeting_morning": "Bonjour",
        "home.greeting_afternoon": "Bon après-midi",
        "home.greeting_evening": "Bonsoir",
        "home.stat_days": "days",
        "home.stat_xp": "XP",
        "home.stat_level": "level",
        "home.stat_average": "average",
        "home.dictation_title": "Today's dictation",
        "home.dictation_badge": "+120 XP if flawless",
        "home.dictation_cta": "Listen and write",
        "home.quick_title": "Pick up quickly",
        "home.tile_dictation": "Dictation",
        "home.tile_dictation_sub": "Write what you hear",
        "home.tile_homophone": "Homophone duel",
        "home.tile_homophone_sub": "a or à?",
        "home.tile_tutor": "AI tutor",
        "home.tile_tutor_sub": "Ask anything",
        "home.tile_story": "Stories",
        "home.tile_story_sub": "French in context",
        "home.word_of_day_title": "Word of the day",
        "home.review_title": "Due for review today",
        "home.review_subtitle": "%d rules are waiting",
        "home.review_empty": "Nothing to review today. You're up to date.",
        "home.weakness_title": "Your weak spot",
        "home.weakness_none": "You haven't made enough mistakes for me to say yet.",
        "home.stories_title": "Stories",
        "home.stories_all": "All stories",
        "home.start": "Start",
        "lessons.title": "Path",
        "lessons.subtitle": "14 lessons, each with its spelling focus",
        "lessons.filter_all": "All",
        "lessons.minutes": "%d min",
        "lesson.intro": "Introduction",
        "lesson.vocabulary": "Vocabulary",
        "lesson.phrases": "Useful phrases",
        "lesson.grammar_tip": "Grammar tip",
        "lesson.cultural_note": "Cultural note",
        "lesson.ortho_spotlight": "Spelling focus",
        "lesson.mark_complete": "Mark as done · +50 XP",
        "lesson.completed": "Done",
        "lesson.loading": "Gemma is preparing the lesson…",
        "lesson.flip": "Flip",
        "lesson.translation": "Translation",
        "lesson.example": "Example",
        "lesson.spelling_note": "Spelling trap",
        "lesson.card_index": "%d / %d",
        "lesson.right": "Right",
        "lesson.wrong": "Wrong",
        "ortho.title": "Spelling",
        "ortho.subtitle": "Eight areas. Every mistake becomes a lesson.",
        "ortho.mastery": "Mastery",
        "ortho.modules": "Modules",
        "ortho.dictation": "Dictation",
        "ortho.dictation_sub": "Listen, write, get corrected",
        "ortho.train": "Practise",
        "ortho.rules": "Rules",
        "ortho.drills": "Exercises",
        "ortho.rule_examples": "Examples",
        "ortho.rule_exceptions": "Exceptions",
        "ortho.mnemonic": "Remember",
        "ortho.check": "Check",
        "ortho.next": "Next",
        "ortho.correct": "Correct",
        "ortho.incorrect": "Not quite",
        "ortho.explanation": "Why",
        "ortho.your_answer": "What you wrote",
        "ortho.expected": "The correct form",
        "ortho.score": "Score",
        "ortho.out_of_20": "%@ / 20",
        "ortho.replay": "Play again",
        "ortho.slower": "Slower",
        "ortho.word_by_word": "Word by word",
        "ortho.spell_it": "Letter by letter",
        "ortho.hint": "Hint",
        "ortho.show_translation": "Show translation",
        "ortho.submit": "Correct me",
        "ortho.finish": "Finish",
        "ortho.mistakes_title": "Your mistakes",
        "ortho.perfect": "Not one mistake. Flawless.",
        "ortho.review_rule": "Review the rule",
        "ortho.type_here": "Type what you hear…",
        "ortho.mastered": "Mastered",
        "ortho.not_started": "Not started",
        "ortho.due_now": "Due",
        "ortho.rules_count": "%d rules",
        "ortho.drills_count": "%d exercises",
        "ortho.session_done": "Session complete",
        "ortho.accuracy": "Accuracy",
        "ortho.again": "Another round",
        "ortho.choose_level": "Choose difficulty",
        "ortho.no_drills": "No exercises for this module yet.",
        "games.title": "Games",
        "games.subtitle": "Ten ways to practise without it feeling like homework",
        "game.score": "Score",
        "game.streak": "Streak",
        "game.round": "Round %d / %d",
        "game.finish": "Finish",
        "game.replay": "Play again",
        "game.correct": "Correct",
        "game.wrong": "Wrong",
        "game.tap_start": "Tap to start",
        "game.loading": "Preparing the round…",
        "game.result": "%d out of %d",
        "game.perfect": "Not a single mistake.",
        "game.xp_earned": "+%d XP",
        "game.hold_record": "Hold to record",
        "game.listening": "Listening…",
        "game.mic_denied": "Microphone not allowed. Enable it in Settings.",
        "game.spin": "Spin the wheel",
        "game.build_sentence": "Build the sentence",
        "game.reset": "Reset",
        "stories.title": "Stories",
        "stories.subtitle": "Four French stories — two of them Romanian at heart.",
        "stories.featured": "FEATURED",
        "stories.all": "All stories",
        "stories.chapters": "%d chapters",
        "stories.minutes": "%d min",
        "story.chapter": "Chapter %d",
        "story.scene_index": "Scene %d / %d",
        "story.loading": "Gemma is writing the scene…",
        "story.previous": "Previous",
        "story.next": "Next",
        "story.finish": "Finish the chapter",
        "story.vocab": "Key words",
        "story.ortho_note": "Word close-up",
        "story.translation": "Translation",
        "profile.default_name": "Friend",
        "profile.level_label": "Level %d",
        "profile.xp_label": "%d XP",
        "profile.xp_to_next": "%d to level %d",
        "profile.stat_streak": "Day streak",
        "profile.stat_lessons": "Lessons",
        "profile.stat_badges": "Badges",
        "profile.stat_dictations": "Dictations",
        "profile.rewards_title": "Rewards",
        "profile.mistakes_title": "Your mistake profile",
        "profile.mistakes_empty": "No mistakes recorded. Start a dictation.",
        "profile.mistakes_count": "%d mistakes",
        "profile.voice_title": "Voice",
        "profile.voice_speed": "Speed",
        "profile.voice_gender": "Timbre",
        "profile.voice_ondevice": "On-device only",
        "profile.voice_ondevice_sub": "No network request for the voice.",
        "profile.azure_title": "Azure voice (optional)",
        "profile.azure_hint": "Add an Azure Speech key for the expressive neural voice. Without it, Limbator uses the on-device neural voice.",
        "profile.azure_key": "Azure Speech key",
        "profile.azure_region": "Region (e.g. westeurope)",
        "profile.azure_save": "Save and test",
        "profile.azure_clear": "Clear the key",
        "profile.native_language_title": "Native language",
        "profile.level_title": "Your level",
        "profile.gemma_title": "The Gemma 4 model",
        "profile.gemma_ready": "Ready · 100% offline",
        "profile.gemma_loading": "Downloading / loading…",
        "profile.gemma_failed": "Failed — tap to retry",
        "profile.tutor_title": "AI tutor",
        "profile.tutor_subtitle": "Chat, ask, request examples",
        "profile.cache_title": "Audio cache",
        "profile.cache_clear": "Clear (%@)",
        "profile.reset_title": "Reset profile",
        "profile.reset_subtitle": "Erase everything and start over",
        "profile.reset_confirm": "Reset everything?",
        "profile.reset_action": "Reset",
        "profile.cancel": "Cancel",
        "profile.mastery_title": "Module mastery",
        "profile.words_tracked": "%d words tracked",
        "tutor.title": "Tutor",
        "tutor.badge": "Gemma 4 · on-device",
        "tutor.placeholder": "Ask anything about French…",
        "tutor.greeting": "Bonjour! I'll help you in %@.\n\nI can explain:\n• why “à” and not “a”\n• past participle agreement\n• a word, a phrase, a rule\n• why French doubles its consonants",
        "tutor.unavailable": "\n\n[Gemma unavailable: %@]\n\nThe model downloads on first launch. Local content stays available.",
        "tutor.downloading": "\n\nThe Gemma model is downloading… %d%%\nTry again in a moment.",
        "tutor.warming": "\n\nGemma is starting…\nTry again in a moment.",
        "tutor.send": "Send",
        "tutor.stop": "Stop",
        "component.listen": "Listen",
        "component.spell": "Letter by letter",
        "component.slow": "Slower",
        "component.close": "Close",
        "component.continue": "Continue",
        "component.new_badge": "New badge",
    ]
}
